name: PROJECT-UPDATER - DELIVERY

on:
  push:
    branches: [delivery]

permissions: write-all

jobs:
  sonarcloud-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ${{github.workspace}}
        run: npm install

      - name: Build
        working-directory: ${{github.workspace}}
        run: npm run build

      # - name: Tests
      #   working-directory: ${{github.workspace}}
      #   run: npm test

      - name: ESlint analyze json
        working-directory: ${{github.workspace}}
        run: npm run lint:eslint:json || echo FAILED

      - name: ESlint analyze html
        working-directory: ${{github.workspace}}
        run: npm run lint:eslint || echo FAILED

      - name: Audit dependency
        working-directory: ${{github.workspace}}
        run: npm run audit || echo failed

      - name: Convert Audit dependency report
        working-directory: ${{github.workspace}}
        run: npm run audit:so

      - name: Archive Analyses reports
        uses: actions/upload-artifact@v3
        with:
          name: AudiSo-Analyses-report
          path: ${{github.workspace}}/dist/reports

      # - name: Coverage reports
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Coverage-report
      #     path: ${{github.workspace}}/coverage

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v5

      - name: Run SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io/
          -Dsonar.verbose=false

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    needs: [sonarcloud-analyse]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ${{github.workspace}}
        run: npm install

      - name: Build
        working-directory: ${{github.workspace}}
        run: npm run build

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}